version: "3.9"
services:
  api:
    build: ./TasksApi
    container_name: tasks-api
    ports:
      - "5178:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./TasksApi/tasks.db:/app/tasks.db

  frontend:
    build: ./frontend-blog
    container_name: frontend-blog
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5178
    depends_on:
      - api
